kind: Deployment
apiVersion: apps/v1
metadata:
  name: utils
spec:
  selector:
    matchLabels:
      app: utils
  replicas: 1
  template:
    metadata:
      labels:
        app: utils
    spec:
      containers:
        - name: utils
          image: serbangilvitu/kube-utils:latest